[build]
  # Install devDependencies explicitly, then build
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"              # keeps runtime behavior
  VITE_RUNTIME_ENV = "production"      # custom flag for frontend logic

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
