[build]
  # Install devDependencies explicitly, then build
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"              # keeps runtime behavior
  VITE_RUNTIME_ENV = "production"      # custom flag for frontend logic

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# Static file redirects (highest priority)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Legacy URL redirects
[[redirects]]
  from = "/homepage"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/light-novel-tieng-viet"
  to = "/light-novel-vietsub"
  status = 301
  force = true

[[redirects]]
  from = "/doc-light-novel-vietsub"
  to = "/light-novel-vietsub"
  status = 301
  force = true

[[redirects]]
  from = "/latest-update"
  to = "/light-novel-vietsub"
  status = 301
  force = true

# Clean URL redirects (remove trailing slashes)
[[redirects]]
  from = "/novel/:novelId/"
  to = "/novel/:novelId"
  status = 301
  force = true

[[redirects]]
  from = "/novel/:novelId/chapter/:chapterId/"
  to = "/novel/:novelId/chapter/:chapterId"
  status = 301
  force = true

# API routes should not be caught by SPA fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - handle all other routes with React Router
# This must be LAST to avoid conflicts
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
