[build]
  # Build and ensure _redirects is copied
  command = "npm run build && cp public/_redirects dist/_redirects"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  # Remove NODE_ENV=production to allow devDependencies installation
  VITE_RUNTIME_ENV = "production"      # custom flag for frontend logic

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# All redirects are now handled by the _redirects file
# This avoids duplication and makes maintenance easier
